// <auto-generated />
using DigiNumberApplicationApi.TelegramBot.Infrastructer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiNumberApplicationApi.TelegramBot.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DigiNumberApplicationApi.TelegramBot.Core.Domian.OrderVirtualNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VirtualNumberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VirtualNumberId")
                        .IsUnique();

                    b.ToTable("OrderVirtualNumber", (string)null);
                });

            modelBuilder.Entity("DigiNumberApplicationApi.TelegramBot.Core.Domian.Sudo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("Sudo", (string)null);
                });

            modelBuilder.Entity("DigiNumberApplicationApi.TelegramBot.Core.Domian.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerify")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DigiNumberApplicationApi.TelegramBot.Core.Domian.VirtualNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("EStatusOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("VirtualSessionDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("VirtualSessionDetailsId");

                    b.ToTable("VirtualNumber", (string)null);
                });

            modelBuilder.Entity("DigiNumberApplicationApi.TelegramBot.Core.Domian.VirtualNumberDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VirtualNumberDetails", (string)null);
                });

            modelBuilder.Entity("DigiNumberApplicationApi.TelegramBot.Core.Domian.VirtualSessionDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password2Fa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VirtualSessionDetails", (string)null);
                });

            modelBuilder.Entity("DigiNumberApplicationApi.TelegramBot.Core.Domian.OrderVirtualNumber", b =>
                {
                    b.HasOne("DigiNumberApplicationApi.TelegramBot.Core.Domian.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiNumberApplicationApi.TelegramBot.Core.Domian.VirtualNumber", "VirtualNumber")
                        .WithOne()
                        .HasForeignKey("DigiNumberApplicationApi.TelegramBot.Core.Domian.OrderVirtualNumber", "VirtualNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VirtualNumber");
                });

            modelBuilder.Entity("DigiNumberApplicationApi.TelegramBot.Core.Domian.VirtualNumber", b =>
                {
                    b.HasOne("DigiNumberApplicationApi.TelegramBot.Core.Domian.VirtualSessionDetails", "VirtualSessionDetails")
                        .WithMany()
                        .HasForeignKey("VirtualSessionDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualSessionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
